### ISSUE TITLE
Some messages are not translated in the HTTP response

### ISSUE THREAD

**Issue by krisztianb** [turquoiseowl/i18n#105]
I am experiencing the following strange "phenomena":

I have an input form with several DropDownLists. Examples:

    Select color: [DropDownList] with values: { "Please select color...", "white", "blue"}
    Select type: [DropDownList] with values: { "not defined", "automatic", "semi-automatic"}

All of these values are added on the serverside using:

    dropColor.Items.Add(new ListItem("[[[Please select color...]]]", "NULL"));

Alls of these values are translated in the PO-files. But some are not translated upon request by the i18n module. All texts in the pattern "Please select color..." are not translated. Among them are for instance "Please select brand...", "Please select model...", "Please select type..." and so on.

I tired the following things to narrow the cause down:

* I tried fiddling around with the text "Please select color...". Changed it to only "Please select color" (dots removed) and added a new translation. -> no effect
* I changed the text "Please selec color..." to "not defined", to check wheter there is something wrong with that specific DropDownList control -> now the text was translated. so the control must be fine
* I tried translating on server side manually by calling my wrapper function Lang.GetText("[[[Please select color...]]]") within the constructor of ListItem -> now the text was translated. How could this work and the automatic translation on HTTP response does not work?

Currenclty I have no clue, what really is causing this error. Any ideas?

**Comment by slipdef** [comment]
Looks like HtmlDecode causes issues for us:
http://i.imgur.com/SD7xhu7.png

In PO file we have this with &nbsp included, upon translation HtmlDecode removes &nbsp from msgid, thus localizer can't find a match.

**Comment by turquoiseowl** [comment]
Which code base is this with?

We've just made a change (Issue #200) which may be relevant to this.

**Comment by slipdef** [comment]
Latest, taken from GitHub. Saw #200, it's not relevant. The line causes issues is:
http://i.imgur.com/VtBdYWE.png

**Comment by turquoiseowl** [comment]
Hopefully the patch just pushed does the business.

**Comment by slipdef** [comment]
Awesome! Thanks for the quick turnaround.
