### ISSUE TITLE
Gzip compressed JavaScript file is corrupted

### ISSUE THREAD

**Issue by krisztianb** [turquoiseowl/i18n#109]
Hello, it is me again. :-)

I have a problem with the following .js file:

```
function fileQueueError(file, errorCode, message) {
    try {
        var errorMessage = "";

        switch (errorCode) {
            case SWFUpload.QUEUE_ERROR.QUEUE_LIMIT_EXCEEDED:
                errorMessage = "[[[Sie wollen zu viele Bilder auf einmal hochladen. Löschen Sie bereits vorhandene Bilder oder wählen Sie weniger Bilder aus!]]]";
                break;
            case SWFUpload.QUEUE_ERROR.ZERO_BYTE_FILE:
                errorMessage = "Die ausgewaehlte Datei " + file + " ist ungueltig.\nWaehlen Sie eine andere Datei aus.";
                break;
            case SWFUpload.QUEUE_ERROR.FILE_EXCEEDS_SIZE_LIMIT:
                errorMessage = "Das ausgewaehlte Bild " + file + " ist zu gross!\nEs sind maximal 5MB pro Bild erlaubt.";
                break;
            case SWFUpload.QUEUE_ERROR.INVALID_FILETYPE:
                errorMessage = "Die ausgewaehlte Datei " + file + " ist ungeueltig.\nNur jpg-Dateien sind erlaubt.";
                break;
            default:
                errorMessage = "code: " + errorCode + " mess: " + message;
                break;
        }

        alert(errorMessage);
    } catch (ex) {
        this.debug(ex);
    }
}
```

I checked everything I could:
- file is UTF-8 encoded
- i18n.WhiteList contains *.js in the web.config file
- message is put into the correct messages.po file
- message is translated within the messages.po file
- i18n.LocalizedApplication.Current.ContentTypesToLocalize is not set

and still the message is not being translated.

This is the response header:

```
Accept-Ranges   bytes
Content-Length  10124
Content-Type    application/x-javascript
Date    Thu, 28 Nov 2013 11:15:14 GMT
Etag    "2d7284c128ecce1:0"
Last-Modified   Thu, 28 Nov 2013 10:58:22 GMT
Server  Microsoft-IIS/7.5
X-Powered-By    ASP.NET
```

Do you have any ideas what could possibly be wrong?

**Comment by gitsno** [comment]
This issue is now resolved in a commit in #193 
Note that the fix prevents corruption of content that is compressed before it reaches the i18n module, it does not localize within the compressed content, so if you need to have nuggets in static files localized you should turn off static file compression, but having static file compression turned on will no longer result in corrupt responses.
