### ISSUE TITLE
Installing i18n packge via Nuget breaks application

### ISSUE THREAD

**Issue by menaheme** [turquoiseowl/i18n#117]
having problems, just setting things up. 
1. i installed the nuget i18n 1.0.8 to an existing MVC4 app , added the entries to the web config and i get the YSOD saying "could not load type 'i18n.LocalizingModule' from assembly i18n". , i looked inside the i18n assembly and indeed the module isn't there.

also ,
2. the post build action was not registered by the Nuget, 
3. plus, the post build assembly is built for x86 instead of 'Any', VS warns me about this,(my dev station is x64, and all my projects are 'Any'.)

**Comment by StanleyGoldman** [comment]
nuget is still showing 1.0.8...
Did you ever complete the update to the nuget package?

**Comment by turquoiseowl** [comment]
Sorry, no.
