### ISSUE TITLE
Using  BlackList fires error 'Illegal characters in path.'

### ISSUE THREAD

**Issue by mdmoura** [turquoiseowl/i18n#149]
Hello,

I added the following to my Web.config file:

```
<add key="i18n.WhiteList" value="*.cs;*.cshtml" />
<add key="i18n.BlackList" value="*.generated.cs" />
```

When I run it I get the following error:

```
'settings.BlackList' threw an exception of type 'System.ArgumentException': 'Illegal characters in path.'
```

The WhiteList works fine ... Any idea why this happens?

Thank You,
Miguel

**Comment by muratbaseren** [comment]
I solved this problem.

I changed BlackList value from ".\js\kendo;.\js\angular;.\*\dist"  to  "js\kendo;js\angular;dist"
