### ISSUE TITLE
Exception "Request is not available in this context " on startup 

### ISSUE THREAD

**Issue by jonnybee** [turquoiseowl/i18n#168]
when initializing application.

WebConfigSettingService throws this exception when trying to access the HttpContext.Current.Request.ApplicationPath during Application_Start. 

When using the simple ioc Container the services were not instantiated until the first call was made (like lazy loading) by using a lambda to register. Now with IRootServices these are instantiated immediately. 

I would suggest that DefaultRootServices is modified to have private member fields and make translationRepository, testLocalizer and nuggetLocalizer as Lazy<T> to delay when the objects are created. If anyone wants to create their own (modified) implementation of any of the services they should also create their own implementation of IRootServices.

I would also suggest to change Current to a property and instantiate in getter if not set. I would like to do this: 
  i18n.LocalizedApplication.Current = new LocalizedApplication(new My18nRootServices())
  {
      DefaultLanguage = "no",
      // Change from the of temporary redirects during URL localization
      PermanentRedirects = true,
  };

WITHOUT being forced to have Current set to the default LocalizedApplication first (that creates the DefaultRootServices that creates an instance of WebConfigSettingService that causes the exception in my case). 

I can provide PR if you would like that.

**Comment by turquoiseowl** [comment]
Sounds good to me, a PR will be gratefully received.
