### ISSUE TITLE
Consider support for translation of parameters

### ISSUE THREAD

**Issue by jonnybee** [turquoiseowl/i18n#169]
to support translation like this: 
    [DisplayName("[[[CountryCode]]]")]
    [Required(ErrorMessage = "[[[%0 is required|||(((CountryCode)))]]]")]
    [MaxLength(20, ErrorMessage = "[[[%0 must be %1 characters or less|||(((CountryCode)))|||20]]]")]
    public string CountryCode { get; set; }

and have the translated name of field merged into error message. 

Ideally code should probably use [[[ and ]]]  on the parameter as well - but I could not get the parsing to run OK so I chose to use ((( and ))) as default indicators inside the parameters section. 

My implementation does require PostBuild task to do 2 runs on each file but still runs fast enough. 

I have the necessary changes in my private repo - if the issue is accepted.

**Comment by turquoiseowl** [comment]
As they say, most problems in software can be solved by another level of indirection.

I like your proposal. It will reduce the number of messages to translate.

Some others on here may want to chip in.
