### ISSUE TITLE
fix doc

### ISSUE THREAD

**Issue by lazareveugene** [turquoiseowl/i18n#172]
add this lines to global.asax.cs template 

			
            // Blacklist content types from being nuggets 'processed'. This is defaults
			//LocalizedApplication.Current.ContentTypesToLocalize = new Regex(@"^(?:(?:(?:text|application)/(?:plain|html|xml|javascript|x-javascript|json|x-json))(?:\s*;.*)?)$");

            // Blacklist certain URLs from being nuggets 'processed'. This is defaults
            //LocalizedApplication.Current.UrlsToExcludeFromProcessing = new Regex(@"(?:\.(?:less|css)(?:\?|$))|(?i:i18nSkip|glimpse|trace|elmah)");

            // This line can be used to disable URL Localization.
            //((DefaultRootServices)LocalizedApplication.Current.RootServices).earlyUrlLocalizer = null;

**Comment by turquoiseowl** [comment]
Done it, thank you.
