### ISSUE TITLE
Consider to split WebConfigSettingService 

### ISSUE THREAD

**Issue by jonnybee** [turquoiseowl/i18n#173]
into two classes: WebConfigSetttingService and ExeConfigSettingService. 

.NET has HttpRuntime.AppDomainAppVirtualPath that will provide a safe virtual path - not depending on having access to HttpContext.Current.Request (which is unavailable in Application_Start). 

I am not able to pass inn HttpRuntime.AppdomainAppVirtualPath as parameter as the CTOR vwill assume it is the fill path to an EXE file configuration and use Configuration.OpenMappedExeConfiguration vs WebConfigurationManager.OpenWebConfiguration. 

I assume this may also be helpful when moving into an OWIN runtime environment.

So I'd rather have this CTOR in WebConfigSettingService 

public WebConfigSettingService(string configLocation = null) : base(configLocation)
{
	try
	{
	    var configPath = configLocation ?? HttpRuntime.AppDomainAppVirtualPath;
             _configuration = WebConfigurationManager.OpenWebConfiguration(configPath);
	    _settings = _configuration.AppSettings;
	}
	catch (ConfigurationErrorsException e)
	{
		var eNew = new ConfigurationErrorsException("Could not load configuration. Either incorrect path was sent in or if no path was sent in web.config could not be found where expected",e);
		throw eNew;
	}
}

**Comment by turquoiseowl** [comment]
If you say it works, that's fine by me. I'm not sure why we are using ExeConfigurationFileMap. Does an ASP.NET application ever use that? @rickard?

**Comment by jonnybee** [comment]
Hmm, that is a good question. Maybe this class should rather use OpenWebConfiguration when a parameter is supplied and I18N wouldn't have a need for another configuration class.

**Comment by jonnybee** [comment]
ExeConfigurationFileMap is used in the i18n.PostBuild application to open a config file in an exact location. All webapps should use OpenWebConfiguration. So my recommendation would be to split (and have separation of concern) between these use cases.

**Comment by jonnybee** [comment]
Or add a new parameter to constructor to specify whether configPath is absolute or relative. 
Ex:
public WebConfigSettingService(string configLocation = null, bool isAbsolutePath = false) : base(configLocation)
{
	//http://stackoverflow.com/questions/4738/using-configurationmanager-to-load-config-from-an-arbitrary-location/4746#4746
	try
	{


		if (configLocation != null)
		{
			if (isAbsolutePath)
			{
				//ConfigurationFileMap fileMap = new ConfigurationFileMap(configLocation); //Path to your config file
				//_configuration = ConfigurationManager.OpenMappedMachineConfiguration(fileMap);
				ExeConfigurationFileMap fileMap = new ExeConfigurationFileMap();
				fileMap.ExeConfigFilename = configLocation;
				_configuration = ConfigurationManager.OpenMappedExeConfiguration(fileMap, ConfigurationUserLevel.None);
				//_settings = (AppSettingsSection)_configuration.GetSection("AppSettings");
				_settings = _configuration.AppSettings;
			}
			else
			{
				_configuration = WebConfigurationManager.OpenWebConfiguration(configLocation);
    			_settings = _configuration.AppSettings;
			}
		}
		else
		{
			//No config file was sent in so we use default one
			_configuration = WebConfigurationManager.OpenWebConfiguration(HttpContext.Current != null ? HttpContext.Current.Request.ApplicationPath : null);
			_settings = _configuration.AppSettings;
		}
	}
	catch (ConfigurationErrorsException e)
	{
		var eNew = new ConfigurationErrorsException("Could not load configuration. Either incorrect path was sent in or if no path was sent in web.config could not be found where expected",e);
		throw eNew;
	}
}

**Comment by turquoiseowl** [comment]
Yes, looks right. Would it be more accurate to have a param called isVirtualPath (in place of !isAbsolutePath)?
