### ISSUE TITLE
Consider to add support for visualize translation

### ISSUE THREAD

**Issue by jonnybee** [turquoiseowl/i18n#175]
We are using I18N in our Application and during testing we would like to add a tag / visualization to all texts that I18N has found and translated. This is useful for testers in identifying strings that have not been marked correctly for translation in code/markup etc which may otherwise pass undetected.

We want to use the standard translation while running the app and added a config setting "i18n.VisualizeTokens" that allows us to set the flag to true/false and when true to add a configured token at start/end of translated text. 

We chose to use "!" character before and after translated text to tag this as a translated string. The character/string is also configurable in web.config.

Does this make sense to add to standard I18N? 

I have code in private repo and can supply PR if you are interested.

**Comment by turquoiseowl** [comment]
Yes, that sounds like a nice addition to the library. A PR would be welcome.

**Comment by gitsno** [comment]
I'd say this could be closed - implemented in #176 and #192
