### ISSUE TITLE
add some improvements

### ISSUE THREAD

**Issue by lazareveugene** [turquoiseowl/i18n#178]
i can't create proper pull request without broken formatting

so i create issue to add some lines to files

src/i18n/ResponseFilter.cs

change line 93: 
if (page != null && page.IsPostBack && !String.IsNullOrEmpty(entity) && !String.IsNullOrEmpty(entity.Replace("\r","").Split('\n')[0])) {

this is needed for proper handle requests

src/i18n.Domain/Concrete/POTranslationRepository.cs

add lines from 134: 
var templateFilePath = GetAbsoluteLocaleDir() + "/messages.pot";
            var POTDate = DateTime.Now;
            if (File.Exists(templateFilePath))
            {
                POTDate = File.GetLastWriteTime(templateFilePath);
            }

add lines from 184:
stream.WriteLine("\"Project-Id-Version: \\n\"");
                stream.WriteLine("\"POT-Creation-Date: " + POTDate.ToString("yyyy-MM-dd HH:mmzzz") + "\\n\"");
                stream.WriteLine("\"PO-Revision-Date: " + DateTime.Now.ToString("yyyy-MM-dd HH:mmzzz") + "\\n\"");
                stream.WriteLine("\"MIME-Version: 1.0\\n\"");
                stream.WriteLine("\"Content-Type: text/plain; charset=utf-8\\n\"");
                stream.WriteLine("\"Content-Transfer-Encoding: 8bit\\n\"");
                stream.WriteLine("\"X-Generator: i18n.POTGenerator\\n\"");
                stream.WriteLine();

add lines from 295:
stream.WriteLine("\"Project-Id-Version: \\n\"");
                stream.WriteLine("\"POT-Creation-Date: " + DateTime.Now.ToString("yyyy-MM-dd HH:mmzzz") + "\\n\"");
                stream.WriteLine("\"MIME-Version: 1.0\\n\"");
                stream.WriteLine("\"Content-Type: text/plain; charset=utf-8\\n\"");
                stream.WriteLine("\"Content-Transfer-Encoding: 8bit\\n\"");
                stream.WriteLine("\"X-Generator: i18n.POTGenerator\\n\"");
                stream.WriteLine();

this is need for support editing in i18n apps

**Comment by turquoiseowl** [comment]
Done as request. Let me know if I got anything wrong.

I had the same problem as you with those files! Thanks for persevering.

**Comment by lazareveugene** [comment]
Cool, i 'll check

Also I want to add plural support on next week
22.01.2015 19:40 пользователь "Martin Connell" <notifications@github.com>
написал:

**Comment by lazareveugene** [comment]
when you paste the code you got dublicate lines
remove this lines
POTranslationRepository.cs 293
POTranslationRepository.cs 182

other is ok

**Comment by turquoiseowl** [comment]
There is now a mixture of ```\\n``` and ```\n``` in those string literals.

Please confirm which is correct.

**Comment by turquoiseowl** [comment]
I'm guessing it should be ```\\n``` otherwise you're outputting a newline followed by the closing double quote on that newline.

**Comment by lazareveugene** [comment]
Hello,

yeah, it should be \\n

we need to pass escaped newline

Лазарев Евгений
mailto: lazareveugene@gmail.com
GoogleTalk: lazareveugene@gmail.com
<lazareveugene@gmail.com>SKYPE: lazareveugene
SIP: 84773@sip.zadarma.com
Cellular: +79058077697

2015-01-23 17:24 GMT+05:00 Martin Connell <notifications@github.com>:

**Comment by turquoiseowl** [comment]
Okay, done that. Please confirm it outputs as expected.

**Comment by lazareveugene** [comment]
hello,

also please remove this lines of code POTranslationRepository.cs
293 and 182

as you can see this lines already outputed to the stream

Лазарев Евгений
mailto: lazareveugene@gmail.com
GoogleTalk: lazareveugene@gmail.com
<lazareveugene@gmail.com>SKYPE: lazareveugene
SIP: 84773@sip.zadarma.com
Cellular: +79058077697

2015-01-23 18:25 GMT+05:00 Martin Connell <notifications@github.com>:

**Comment by turquoiseowl** [comment]
Done.

**Comment by lazareveugene** [comment]
cool, now that's all

Здравствуйте,



Лазарев Евгений
mailto: lazareveugene@gmail.com
GoogleTalk: lazareveugene@gmail.com
<lazareveugene@gmail.com>SKYPE: lazareveugene
SIP: 84773@sip.zadarma.com
Cellular: +79058077697

2015-01-23 18:34 GMT+05:00 Martin Connell <notifications@github.com>:
