### ISSUE TITLE
Can not disable URL Localization

### ISSUE THREAD

**Issue by MickeLarsson** [turquoiseowl/i18n#183]
The previous way of disabling early url localization does not longer work (after 21th of december).
The current property is read only, and I can't figure out a way to get around that.

These lines from the readme does not longer compile.
```
// This line can be used to disable URL Localization.
i18n.LocalizedApplication.Current.EarlyUrlLocalizerService = null;
```

**Comment by turquoiseowl** [comment]
Hopefully this fixes it: https://github.com/turquoiseowl/i18n#disabling-url-localization

**Comment by MickeLarsson** [comment]
:+1:
