### ISSUE TITLE
Incorrect HtmlDecode in NuggetLocalizer

### ISSUE THREAD

**Issue by gitsno** [turquoiseowl/i18n#200]
At the end of the ProcessNuggets method in i18n.NuggetLocalizer the return calls HtmlDecode on the message

    return HttpUtility.HtmlDecode(message);

I'm pretty sure that should be HtmlEncode. The MsgId gets decoded earlier and the return message should surely be encoded not decoded? I'm having problems with a case where I have to return XML and an ampersand in a nugget in the XML is not encoded after translation. I tried changing that HtmlDecode to an HtmlEncode and it fixes my problem, I just want to see if I'm missing something and there is some case where it does need to be a decode?

**Comment by turquoiseowl** [comment]
I don't think you were missing anything. A fix is in the repo. Cheers.
