### ISSUE TITLE
URL routing do not work with ActionName atribute in 2.1.1.0 version

### ISSUE THREAD

**Issue by tomasr78** [turquoiseowl/i18n#201]
It seems that something wrong with routing then Action contain ActionName attribute.

Very easy to reproduce...

Remove HOME controller from default Urls adding new URL mapping

//New routing
routes.MapRoute("Custom", "{action}", new { controller = "Home", action = "Index" });

//Added by default
routes.MapRoute("Default", "{controller}/{action}/{id}", new { controller = "Home", action = "Index", id = UrlParameter.Optional });

Remove default language from url using

i18n.UrlLocalizer.UrlLocalizationScheme = i18n.UrlLocalizationScheme.Scheme2; 

Add new action to Home controller with ActionName.

        [ActionName("pdf-word")] 
        public ActionResult Pdf_Word()
        {
            return View("pdf-word");
        }

Add any new language, for example Lithuanian, LT. 

Run project, change language to LT and try to check URL which is generated by Action public ActionResult Pdf_Word()

The url will appears like

http://localhost:1892/pdf-word

without language selector though all other url will contain language selector in URL /LT/

This problem appears after updating to new 2.1.1.0 version from NuGet, the old 2.0 version works fine.

**Comment by turquoiseowl** [comment]
We have just modified language tag detection in the url which I expect is causing this.

Before, language tags had to begin with 2 chars. Now, they may begin with 2 or 3 chars. The string ```pdf-word``` is being matched as a language tag when it wasn't before.

I feel the change from 2 to 3 chars was correct in that it corresponds to the full BCP 47 spec. But it does mean that we are more likely to get false matches like this.

If you happened to call that file ```pd-word``` before then the same problem would arise.

For now, to avoid the problem with this setup, don't use an action name in the root of the path that matches:

```
Regex(@"^([a-zA-Z]{2,3})(?:-([a-zA-Z]{4,5}))?(?:-([a-zA-Z]{2}|[0-9]{3}))?(?:\-x-([a-zA-Z0-9]{4,}))?$", RegexOptions.CultureInvariant)
```

Maybe some kind of cross-referencing is required as part of the language tag parsing. Although IIRC this part was designed to impose minimal overhead.

Other ideas welcome.

**Comment by tomasr78** [comment]
>Before, language tags had to begin with 2 chars. Now, they may begin with 2 or 3 chars. The string pdf-word is being matched as a language tag when it wasn't before.

That's not quite true, because ActionName pdf-powerpoint works fine and it start exactly as pdf-word with three symbols and follow by dash. Working example below


        [ActionName("pdf-powerpoint")] 
        public ActionResult Pdf_PowerPoint()
        {
                  return View("");
        }

**Comment by turquoiseowl** [comment]
Not sure how that first statement is not true. Reference is only made to the beginning of the language tag AKA the language sub tag. pdf-powerpoint will never match, before nor now.

pdf-word is being picked up as a complete language tag, "word" matching a script subtag.

**Comment by tomasr78** [comment]
Could you make RegEx property public and let users modify Language Tag detection, I will never use subtags to define language in URL and this cause problems in my project.

**Comment by turquoiseowl** [comment]
That would be possible.

Before doing that, however, have you tried the following suggestions?:

https://github.com/turquoiseowl/i18n#exclude-urls-from-being-localized

**Comment by tomasr78** [comment]
I am not sure how this could help me to keep proper url. I need to localize action pdf-word and keep correct url with language selector like this http://domain/LT/pdf-word

**Comment by turquoiseowl** [comment]
Perhaps something like:

```
i18n.UrlLocalizer.QuickUrlExclusionFilter = new System.Text.RegularExpressions.Regex(@"^pdf.*");
```

**Comment by turquoiseowl** [comment]
In i18n, URL localization is separate from content localization. I'm thinking that the above will still localize the content under the default PAL, but coul dbe wrong on that. I'd appreciate it if you tested it. Thanks.

**Comment by tomasr78** [comment]
Using your provided code I still get wrong url format without language tag, should be http://localhost:1892/LT/pdf-word  instead I get http://localhost:1892/pdf-word 
I do not see any solution with i18n NuGet version just to uninstall it and use source version from github by modifying url parsing RegEx replacing it from 2.0 version.

In future release please make RegEx property public to let user modify url detection algorithm or just add several url detection modes.

**Comment by turquoiseowl** [comment]
Requested changes just pushed to the repo.

**Comment by tomasr78** [comment]
You are fast! Thank you very much! Will you create NuGet update soon?

**Comment by turquoiseowl** [comment]
Yes.

**Comment by tomasr78** [comment]
Could you push updated version to NuGet today?

**Comment by turquoiseowl** [comment]
Yes, I'm pleased to say that v2.1.3 is now on NuGet.
