### ISSUE TITLE
Include all javascript files except selected

### ISSUE THREAD

**Issue by mmunchandersen** [turquoiseowl/i18n#203]
Adding *:js to web.config -> i18n.WhiteList will also include all libraries in the nugget production processing. I'm using kendo ui which deep in the its code has some nuggets like [[[e.x1,o.y1],[e.x2,o.y1]]].

Since I'm sending out my .pot files to translators via crowdin having these non-nuggets in the files causes confusion.

I can fix the issue by adding the individual javascript files to i18n.WhiteList, however this will fast become bad practise.

How can combine the various whitelist and blacklist to include all javascript but a few selected?

BTW this is a truly great project.

**Comment by turquoiseowl** [comment]
There is a problem with the default nugget markup in that it clashes with JSON arrays.

If that is your problem, a solution is to use alternative nugget markup e.g. ```[#[message]#]```. Have you considered that? The readme documents how to do that.

**Comment by mmunchandersen** [comment]
thanks. changing the nugget markup does the trick
