### ISSUE TITLE
i18n PostBuild doesn't update tenant files

### ISSUE THREAD

**Issue by floo51** [turquoiseowl/i18n#207]
My locale folder looks like this :
- fr
- en
- fr-x-tenant1
- fr-x-tenant2

When I'm executing the PostBuild to update po files, it goes through `fr` and `en` folders but not through tenant folders.

When `GetAvailableLanguages()` is called, a verification of the name of the directories toward `CultureInfo` happens, that's where the tenant directories are put aside. Is this a meant behaviour ?

**Comment by turquoiseowl** [comment]
I suspect that is a bug. The private-use subtag / multi-tenant support was added as a contribution to the library. If you are able to submit a fix that would be most welcome.

**Comment by couraud** [comment]
I am using the private-use subtag without this problem and PostBuild
successfully updates the private-use po files. However, my folders are in
this format: fr-FR-x-tenant1.

It might be worth trying fr-FR-x-tenant1 to see if it's a regex issue.




*Roly Walter*
Appraisd.com
<http://www.appraisd.com/?src=sig_rw&utm_source=sig&utm_medium=em&utm_campaign=rw>

[image: Our LinkedIn page] <http://www.appraisd.com/company/appraisd> [image:
Our Facebook page] <https://www.facebook.com/Appraisd> [image: Our Twitter
feed] <https://twitter.com/appraisd>

mo +44 7812 079132
dd +44 20 7202 7979

**Comment by floo51** [comment]
@couraud Doesn't work any better with your syntax. You might have an older version ?

@turquoiseowl Will take a look at it and see what's the best option to make sure the folder should actually be processed.
