### ISSUE TITLE
Urls for ActionResults of Controller named Map fail

### ISSUE THREAD

**Issue by mmunchandersen** [turquoiseowl/i18n#208]
In an asp.net mvc website I have a Controller called MapController.
When I hook up any ActionResult function in the MapController the language tag (en/fr) is not prefixed to the url:

@Html.ActionLink("[#[Map reporting]#]", "Index", "Map") becomes 
<a href="/Map">Map reporting</a> (should have been <a href="/en/Map">Map reporting</a>)

If I change the name of the controller to MappingController the url is prefixed correctly:

@Html.ActionLink("[#[Map reporting]#]", "Index", "Mapping") becomes 
<a href="/en/Mapping">Map reporting</a>

I have updated to the latest version and tried everything else (I think) before renaming the controller.

**Comment by turquoiseowl** [comment]
Is it the same for any 3-letter controller name? E.g XyzController?

**Comment by turquoiseowl** [comment]
If so, please see #201.

**Comment by mmunchandersen** [comment]
Yes, I see the same pattern with a controller named AbcController.
I can live with not naming controllers matching the language tag detection pattern as stated in https://github.com/turquoiseowl/i18n/issues/201

**Comment by turquoiseowl** [comment]
Right you are.

 

Just to note down an idea I've had on this point: we could generate the language tag regex dynamically during runtime initialization based on the ApplicationLanguages found.
