### ISSUE TITLE
Disable default language URL

### ISSUE THREAD

**Issue by tomasr78** [turquoiseowl/i18n#212]
I use i18n.UrlLocalizationScheme.Scheme2 schema to url tagging and default language tag is not added to web page url by default.  

i18n.UrlLocalizer.UrlLocalizationScheme = i18n.UrlLocalizationScheme.Scheme2;

So the same web page content can be accessed from two different url like www.mydomain.com and www.mydomain.com/en. This is very harmful for web page ranking on search engines and I am looking how to disable default language url www.mydomain.com/en
Do you have any ideas how to overcome this?

**Comment by turquoiseowl** [comment]
In Scheme2, any URLs to the default language (e.g. /en) in the page should be converted as part of Late URL localiztion to remove the langtag. Would you confirm whether or not this is the case with your app.

Further, any request URLs with the default language should be redirected to to a URL without the langtag when it arrives, as part or Early URL localization. My understanding of Google is that it will follow the redirect and cache the destination URL. Thus there is no duplicate URL as far as Google is concerned. Is that not right?

NB: there is a setting to control the type of redirect i18n does in this case:

```
i18n.LocalizedApplication.Current.PermanentRedirects
```

**Comment by tomasr78** [comment]
>In Scheme2, any URLs to the default language (e.g. /en) in the page should be converted as part of >Late URL localiztion to remove the langtag. Would you confirm whether or not this is the case with >your app.

**Comment by turquoiseowl** [comment]
?
