### ISSUE TITLE
Change AppLanguages

### ISSUE THREAD

**Issue by kenyeung128** [turquoiseowl/i18n#214]
Hi, is there anyway to change the AppLanguages dynamically? Thanks.

**Comment by turquoiseowl** [comment]
Yes, i18n will pick up new languages as their folders are added under ```./locale/```. No need to restart the server. In the same way it will also pick up modifications to existing translations as they are saved to the file system.

**Comment by kenyeung128** [comment]
yes, i got that. But what about not depending on the folders structure, i
would like explicitly control which languages are available, without having
to add/remove the folder.

**Comment by turquoiseowl** [comment]
You mean per-request?

There's no easy way to do that.

The non-easy way would be to subclass i18n.TextLocalizer and override TextLocalizer.GetAppLanguages with your own logic.

To inject that, look at subclassing DefaultRootServices and setting that via the i18n.LocalizedApplication.RootServices accessor.

**Comment by kenyeung128** [comment]
on the application level.

e.g. i got 5 languages in locale folder, but i would like to have 2 of it
available with an configuration in c#.

**Comment by turquoiseowl** [comment]
web.config:

```
  <appSettings>
    ....
    <add key="i18n.AvailableLanguages" value="en;se" />-->
  </appSettings>
```

**Comment by turquoiseowl** [comment]
Note that the i18n.AvailableLanguages primarily controls the folders updated by PostBuild procedure. But is does also control the languages loaded at runtime too. But that means that any excluded language folders won't be updated when you run PostBuild.

**Comment by kenyeung128** [comment]
ok thanks. For now, I make an extra lookup to check if the language is configured in the application.
