### ISSUE TITLE
Javascript only translated on first request

### ISSUE THREAD

**Issue by ninjacarr** [turquoiseowl/i18n#217]
I'm experiencing some weird behaviour when moving from dev (IIS express) to IIS.

In development, nuggets are picked up and translated correctly both in code, razor views, and in static JS files on all requests.

In production, code and razor views are still translated for all requests. However, JS files are only translated on the first HTTP request. For the second and following requests, the original JS file seems to be returned with nugget tags and original strings visible, as if they were never touched by the httpmodule.

* If the web application is given a 45 second pause **without any HTTP requests to that specific JS file**, the next request will return a properly translated version of it.
* The first request after recycling the app pool (for example by making a web.config change) is also translated correctly.
* The same client can quickly request 10 different JS files, and they will all be translated correctly
* If **any** client makes a request to a given JS file, there will be another 45 seconds before **any** client will be able to request the same file and have it translated.

Is this some kind of caching issue? The 45 seconds seem oddly specific.

**Comment by turquoiseowl** [comment]
It certainly looks like a caching issue. This wouldn't be the first time i18n has had problems with cache settings. If you search the back issues there are several WRT IIS cache settings.

**Comment by ninjacarr** [comment]
You're right - it was likely caused by the compression caching mechanism in IIS.
Solved it by disabling static content compression. Thanks!
