### ISSUE TITLE
Redirects not being localized

### ISSUE THREAD

**Issue by Zeroto** [turquoiseowl/i18n#222]
It seems that when using scheme2 for the urls, that the location header is not localized. This is the same problem as #218. That issue only talks about RedirectToAction, but it looks like both Redirect as well as RedirectToAction are affected by it.

This is probably the offending line: https://github.com/turquoiseowl/i18n/blob/master/src/i18n/Concrete/EarlyUrlLocalizer.cs#L121

This supplies a true for the incomingUrl parameter which should most likely be false. Though it also looks like LocalizeUrl is only used for the outgoing urls, so that parameter can most likely be removed completely.

**Comment by turquoiseowl** [comment]
Version 2.1.5 includes fixes for Scheme2. I'm closing this in the hope that it fixes your problem. Feel free to re-open necessary. Thanks.

**Comment by ajbeaven** [comment]
Problems still exist at least for RedirectToAction on 2.1.5.
