### ISSUE TITLE
How to ignore '[[[ ]]]' in comments in .cs file

### ISSUE THREAD

**Issue by kenyeung128** [turquoiseowl/i18n#223]
Hi, I have this code as comment in .cs. which contains [[[ and ]]]

        /// <summary>
        /// Transform translation text with [[[ => ((( and  ]]] => )))
        /// </summary>

however, msgid was interpreted as  " => ((( and  ", what can i do to ignore the translation in comments which export to .pot file?

**Comment by turquoiseowl** [comment]
At present, the library doesn't support such differentiation during nugget extraction, sorry.

We can mark this as a feature request if you like. Off the top of my head it could be done by tweaking the regular expression used to extract nuggets (NuggetParser.m_regexNuggetBreakdown); although anything that would complicate/slow that needs solid justification.

**Comment by turquoiseowl** [comment]
Closing a not going to implement. Please re-open to discuss further.
