### ISSUE TITLE
Translation text within another translation text

### ISSUE THREAD

**Issue by kenyeung128** [turquoiseowl/i18n#224]
Hi,

I have the following scenario where y contains another translation text of x, it doesn't seems y get translated correctly.

var x = string.format("{0} which is [[[ good ]]]", "Apple");

var y = string.format("[[[I want {0}]]]", x);

**Comment by turquoiseowl** [comment]
Correct. Nested nuggets aren't supported at present.

**Comment by turquoiseowl** [comment]
This may possibly help you here:

```
var y = string.format("[[[I want {0}]]]", HttpContext.ParseAndTranslate(x));
```

Ref https://github.com/turquoiseowl/i18n#how-to-get-a-translation-of-a-nugget-in-your-c-code

**Comment by kenyeung128** [comment]
great. Using HttpContext.ParseAndTranslate solved my problem. Thanks a lot!
