### ISSUE TITLE
DNN

### ISSUE THREAD

**Issue by GusBeare** [turquoiseowl/i18n#225]
Hi

just wondered if anyone has tried this with Dotnetnuke?

I'd love to find an alternative to the mess that is the core localisation provider.

Gus

**Comment by turquoiseowl** [comment]
I don't know to be honest. Theoretically it should work with anything that is ASP.NET v4 or later.

**Comment by turquoiseowl** [comment]
Any progress with this? Can I close?

**Comment by GusBeare** [comment]
Sorry, not had time to investigate. So go ahead and close for now. I'll get back here some time when I've tried it out.
