### ISSUE TITLE
Ignore Currency 

### ISSUE THREAD

**Issue by eddygonzalez2000** [turquoiseowl/i18n#227]
Hello, can I configure to not change the currency only the language, for example in Spanish is changing the currency to 1,000 and in English is 1.000, I just want to change the texts inside [[[ ]]]

Thanks

**Comment by turquoiseowl** [comment]
Does https://github.com/turquoiseowl/i18n/issues/108 help?

**Comment by turquoiseowl** [comment]
Is this still an issue?
