### ISSUE TITLE
ASP.NET MVC 6 support

### ISSUE THREAD

**Issue by mdmoura** [turquoiseowl/i18n#229]
Hello,

Is there any plan to support ASP.NET MVC 6?

Thank You,
Miguel

**Comment by turquoiseowl** [comment]
I haven't looked at that yet. Have you tried getting it to work?

**Comment by mdmoura** [comment]
Not yet ... ASP.NET MVC 6 works really differently.

I am still looking at it to check the best way to include PO files and generate links.

Not only include it in MVC6 but making it compatible with Angular ... 

I mean an approach that works well and in similar way in both cases.

**Comment by turquoiseowl** [comment]
The i18n library targets ASP.NET rather than ASP.NET MVC. So it may or may not work as is.

**Comment by VladMukhitdinovLic** [comment]
We are using it for our ASP.NET MVC 5 projects. And it works great.

**Comment by turquoiseowl** [comment]
Can I close this?
