### ISSUE TITLE
build warning (processor architecture)

### ISSUE THREAD

**Issue by mmunchandersen** [turquoiseowl/i18n#230]
Everything works, howerver, I'm getting the following warning in my asp.net mvc5 project:

"There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "i18n.PostBuild", "x86". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project."

My web-project is set to "Any CPU" under "Project properties" -> "Build" -> "platform target"

**Comment by turquoiseowl** [comment]
Please re-open if necessary, thanks.
