### ISSUE TITLE
Is it possible to keep default Url

### ISSUE THREAD

**Issue by phat1234** [turquoiseowl/i18n#245]
Hello 
Im trying to url like this http://project/Signin, i don't want to change http://project/en/SignIn or http://project/zh/Signin. if a language changed

Is it possible to do that?
Thanks

**Comment by berniezhao** [comment]
Check i18n.UrlLocalizer.UrlLocalizationScheme?

**Comment by turquoiseowl** [comment]
That's right, it sounds like ```i18n.UrlLocalizationScheme.Void```. See https://github.com/turquoiseowl/i18n#project-configuration.

**Comment by phat1234** [comment]
Thank you very much, the problem have solved.
I do not know what happened, i try to do before and maybe cookie i18n.langtag is not expires.

**Comment by miemengniao** [comment]
I guess it cause by the sample code.  in startup sample code, the cookies's name：i18n_langtag, but in the change language sample code. the cookie's name is :i18n.langtag
