### ISSUE TITLE
Is it possible to use multiple PO files?

### ISSUE THREAD

**Issue by phat1234** [turquoiseowl/i18n#247]
Hello

I want to use 2 files: one is messages, another one for dynamic context .
any idea?

thanks.

**Comment by turquoiseowl** [comment]
The i18n library is dynamic in the sense that changes to PO files are picked up at server runtime -- no need to restart the server. I don't know whether that helps.

**Comment by phat1234** [comment]
nvm, i solved the problem. 
thanks you very much.
this library very nice
