### ISSUE TITLE
Fun with parenthesis

### ISSUE THREAD

**Issue by rickardliljeberg** [turquoiseowl/i18n#248]
So I got this very strange error in arabic

https://db.tt/5w2o2dqA

- Top left is the rendered view in Chrome with the buttons displaying parenthesis weirdly.

- Bottom Left is chromes inspector showing it's the same in html printout

- Right is the PO file showing the parentheis are different

I also tried with Firefox. looks the same.

**Comment by turquoiseowl** [comment]
Have you looked at the response entity itself to see exactly what's output (in terms of bytes)? It could be a bug in the lib or possibly an encoding issue with UTF-8.

**Comment by rickardliljeberg** [comment]
No we just worked around it by using hyphen instead of parenthesis, it seems I am constantly out of time for digging deeper like that :\
