### ISSUE TITLE
formatting dynamic value for translation

### ISSUE THREAD

**Issue by phat1234** [turquoiseowl/i18n#256]
Hello 
I have string like this :" {0} Win Loss Details" and i tried [[[%0 Win Loss Details|||{0}|||]]]
web.config
<add key="i18n.NuggetBeginToken" value="[[[" />
<add key="i18n.NuggetEndToken" value="]]]" />
<add key="i18n.NuggetDelimiterToken" value="||||" />
<add key="i18n.NuggetCommentToken" value="////" />
<add key="i18n.NuggetParameterBeginToken" value="(((" />
<add key="i18n.NuggetParameterEndToken" value=")))" />
but it does not work.

any idea for this
Thanks.

**Comment by turquoiseowl** [comment]
In what context? string.Format?

**Comment by phat1234** [comment]
Yes
I am on my way now
ex:  if I have String.format("{0} Win Loss Details", type);  -> Type ("Admin", "ShareHolder",....)
so in the file translate, i put in for all of them
"Admin Win Loss Details"
"ShareHolder Win Loss Details"
...
But this way does not good.That's so complicated. any best idea to do that
Thanks.

**Comment by turquoiseowl** [comment]
Hmm, not too sure what you're asking. You can set ```type``` first, e.g.
```
    string type = isAdmin ? "[[[Admin]]]" : "[[[ShareHolder]]]"; /// or whatever
```
then build your localizable formatted string:
```
    string output = string.Format("[[[%0 Win Loss Details|||{0}]]]", type);
```
The above would result in 3 PO messages in the PO files.

**Comment by phat1234** [comment]
yes, I understood.
thanks for your help
