### ISSUE TITLE
i18n.POTGenerator compiled version for VS2015

### ISSUE THREAD

**Issue by tomasr78** [turquoiseowl/i18n#258]
Where I could find compiled i18n.POTGenerator version for VS2015?

**Comment by turquoiseowl** [comment]
There isn't an official build of that for VS2015, yet. You will need to do it yourself from the source.

**Comment by tomasr78** [comment]
What changes should I make in i18n.POTGenerator project to install extension to VS Prof 2015?
I have compile the project and while trying to install package I get error

3/31/2016 10:32:04 AM - Microsoft VSIX Installer
3/31/2016 10:32:04 AM - -------------------------------------------
3/31/2016 10:32:04 AM - Initializing Install...
3/31/2016 10:32:04 AM - Extension Details...
3/31/2016 10:32:04 AM - 	Identifier         : 698f006d-7893-4be1-bdf2-a51c47349941
3/31/2016 10:32:04 AM - 	Name               : i18n.POTGenerator
3/31/2016 10:32:04 AM - 	Author             : -
3/31/2016 10:32:04 AM - 	Version            : 1.0
3/31/2016 10:32:04 AM - 	Description        : Adds a new project menu item to generate a POT file from the cs and cshtml files planning to use the i18n library for internationalization
3/31/2016 10:32:04 AM - 	Locale             : en-US
3/31/2016 10:32:04 AM - 	MoreInfoURL        : 
3/31/2016 10:32:04 AM - 	InstalledByMSI     : False
3/31/2016 10:32:04 AM - 	SupportedFrameworkVersionRange : [4.5]
3/31/2016 10:32:04 AM - 
3/31/2016 10:32:04 AM - 	SignatureState     : Unsigned
3/31/2016 10:32:04 AM - 	Supported Products : 
3/31/2016 10:32:04 AM - 		Microsoft.VisualStudio.Pro
3/31/2016 10:32:04 AM - 			Version : [12.0]
3/31/2016 10:32:04 AM - 		Microsoft.VisualStudio.Pro
3/31/2016 10:32:04 AM - 			Version : [11.0,13.0)
3/31/2016 10:32:04 AM - 
3/31/2016 10:32:04 AM - 	References         : 
3/31/2016 10:32:04 AM - 		-------------------------------------------------------
3/31/2016 10:32:04 AM - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
3/31/2016 10:32:04 AM - 		Name         : Visual Studio MPF 11.0
3/31/2016 10:32:04 AM - 		Version      : [11.0]
3/31/2016 10:32:04 AM - 		MoreInfoURL  : 
3/31/2016 10:32:04 AM - 		Nested       : No
3/31/2016 10:32:04 AM - 
3/31/2016 10:32:04 AM - Signature Details...
3/31/2016 10:32:04 AM - 	Extension is not signed.
3/31/2016 10:32:04 AM - 
3/31/2016 10:32:04 AM - Searching for applicable products...
3/31/2016 10:32:04 AM - Found installed product - Microsoft Visual Studio Professional 2015
3/31/2016 10:32:04 AM - Found installed product - Microsoft Visual Studio Community 2015
3/31/2016 10:32:04 AM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
3/31/2016 10:32:04 AM - Found installed product - Global Location
3/31/2016 10:32:04 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by turquoiseowl** [comment]
#231 may help you.

**Comment by turquoiseowl** [comment]
You may also want to try replacing the reference to Microsoft.VisualStudio.Shell.12.0 with one to Microsoft.VisualStudio.Shell.14.0 (from i18n.POTGenerator project).

**Comment by tomasr78** [comment]
I have made changes in extension.vsixmanifest file and was able to install exception into VS 2015 but I do not find any i18n menu. How to use it?

**Comment by turquoiseowl** [comment]
Please re-open if still an issue. Thanks.

**Comment by cigano** [comment]
[I made this pull request that solves these issues](https://github.com/turquoiseowl/i18n/pull/282). It would be great to publish the VSIX in Visual Studio Gallery.
