### ISSUE TITLE
zh-hans and zh-hant not working

### ISSUE THREAD

**Issue by tomasr78** [turquoiseowl/i18n#259]
I have added zh-hans and zh-hant folders (Chinese simplified and traditional) to Locale folder with messages.po files inside. When I hit my MVC app url www.domain.com/zh-hans I get 404 page not found, other languages works fine. How to add these languages to i18n?

**Comment by turquoiseowl** [comment]
Hmm, not sure. I've have both zh-hans and zh-hant working fine on my site. I can only suggest, if you haven't alreay, copying a language folder you know works into "local\zh-hans". Failing that, debugging the app.

**Comment by turquoiseowl** [comment]
Please re-open if still an issue. Thanks.
