### ISSUE TITLE
How language changing while editing in url ?

### ISSUE THREAD

**Issue by codebuger** [turquoiseowl/i18n#263]
I need to check the messages.po file when each time language changes. Is there any method in i18n plugin firing while changing language in url or any possible way to call a method when language changed in url ?

**Comment by turquoiseowl** [comment]
Short answer is no. That sounds like something you would handle directly in ASP.NET.

Remember, web apps handle one request at a time, so it doesn't really make sense to talk about changes in the URL, other than where you maintain state between requests and that would depend on how you maintain that state.
