### ISSUE TITLE
Release history

### ISSUE THREAD

**Issue by Leftyx** [turquoiseowl/i18n#273]
I've been involved in a project where **i18n** is used.
The VS solution uses NuGet to install i18n and the installed version is **2.1.4.0**.
I was wondering if there are any known breaking changes to consider when upgrading to **2.1.7.0**.
I've checked the release history but nothing is documented.
Going through the code it seems fine to upgrade but maybe some one can give me some more info.

Thanks.

**Comment by turquoiseowl** [comment]
You may need to recompile your code against the new reference but nothing should be broken by the upgrade.

**Comment by Leftyx** [comment]
Thanks for your help. Very much appreciated.
