### ISSUE TITLE
Setting Datetime Format for CultureInfo

### ISSUE THREAD

**Issue by achmstein** [turquoiseowl/i18n#277]
How can I set DateTimeFormat Property for CultureInfo ?
for example:
 Thread.CurrentThread.CurrentCulture =
                Thread.CurrentThread.CurrentUICulture = new CultureInfo(lang) { DateTimeFormat = new DateTimeFormatInfo() };

**Comment by turquoiseowl** [comment]
I'm not clear how this is an issue with i18n.

**Comment by turquoiseowl** [comment]
Please re-open if still an issue, thanks.
