### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by cigano** [turquoiseowl/i18n#284]
I want to contribute with this project writing code and documentation. I didn't find a Wiki, and it should be interesting for this project to have one. 

Additionally, can we add some samples and examples of usage?

**Comment by turquoiseowl** [comment]
Yes, your help will be much appreciated. Both a Wiki and Samples would be great additions. Just now I'm heavily committed to other work but will try to assist as much as possible.

**Comment by cigano** [comment]
It is possible to grant me access to edit the Wiki? I have a lot of contributions to do while using the package with my students.

**Comment by turquoiseowl** [comment]
I've enabled the Wiki and created the first blank page. It should be publicly editable. Let me know if not...

**Comment by cigano** [comment]
Thanks. I'll make some contributions during this week. For now, everything is working.
