### ISSUE TITLE
Support i18n in Microsoft BotBuilder

### ISSUE THREAD

**Issue by kenyeung128** [turquoiseowl/i18n#288]
Hi, it doesn't seems i18n support in Microsoft BotBuilder yet, which is webapi based. I believe it's required some middleware to do that. Would you point me some directions? Thanks.

https://github.com/Microsoft/BotBuilder

**Comment by turquoiseowl** [comment]
I take it from a quick look at BotBuilder it uses Node.js for the server rather than ASP.NET. Is that right?

If so, it would be a case of migrating the LocalizingModule over to whatever Node's equivalent to the ASP.NET request pipeline is.

**Comment by kenyeung128** [comment]
Thanks for your quick reply.

There is a c# version too, it uses webapi controller action, but the result are not translated/used with i18n, displayed as with bracket [[[ Original Text ]]]] , looks like it's bypassed somehow
https://github.com/Microsoft/BotBuilder/tree/master/CSharp

Documentation
https://docs.botframework.com/en-us/csharp/builder/sdkreference/

**Comment by turquoiseowl** [comment]
If it uses webapi, doesn't that mean there is some sort of HTTP server/backend involved? I took it from the quick look I took that that would be a node.js process.

**Comment by kenyeung128** [comment]
Exactly, I need to inject a middleware to parse and translate the text. Thanks.
