### ISSUE TITLE
modular asp.net mvc app

### ISSUE THREAD

**Issue by suddenelfilio** [turquoiseowl/i18n#290]
We are building a mvc web app which "abuses" the Area functionality for modular purposes. We have the main web project let's call it Shell which contains all boilerplate code css, js, and so on...

We have seperate solutions where we also have a mvc web app that we xopy into the shell module\bin => shell\bin , module\css => shell\css\modules\module, module\js => shell\js\modules\module.

as you might guess I would like each module to generate their own .po files and then xcopy them into the shell somehting like:

default the shell => shell\locale\en\messages.po contains the general messages
module1\locale\en\messages.po => shell\locale\en\messages2.po (contains all of the module messages)
module2\locale\en.... and so on for each module we develop.

Will i18n which operates in the context of the shell as well as the modules as they are loaded into the same appdomain pick up and sort of merge all these .po files for the languages "en"?

**Comment by turquoiseowl** [comment]
No, not as it stands. It just looks for one file in each locale folder, messages.po.

However, i18n is fairly modular itself so you could look at your implementation of the |ITranslationRepository interface and inject that. Or extend the standard, POTranslationRepository implementation accordingly. This could be useful standard functionality.

**Comment by suddenelfilio** [comment]
What would the behavior be if one or more files contain the same message key, but different translations for them?
