### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by quangtrang1111** [turquoiseowl/i18n#291]
Hi all,
Does i18n working with .NET Core or do you have any plan to support .NET Core?
Thank you so much

**Comment by turquoiseowl** [comment]
If you mean ASP.NET Core, I don't know TBH. It is down to what's changed. Has anyone tried?

If you mean a non-webapp built under .NET Core, that's different in that i18n is designed specifically for webapps so the answer at present is sorry, no.

**Comment by quangtrang1111** [comment]
I try it on ASP.NET Core and the result is not support :(.

But whatever, thank you again.
