### ISSUE TITLE
Change cookie name to i18n_langtag?

### ISSUE THREAD

**Issue by theneujersey** [turquoiseowl/i18n#296]
We are having some trouble with integration into our system the way it is titled right now. Is there any way to change the cookie name so it has an underscore instead of a period?

**Comment by turquoiseowl** [comment]
There wasn't but is now!

See https://github.com/turquoiseowl/i18n#project-configuration for instructions. (You'll need to pull the latest repo until I push to nuget.)

**Comment by theneujersey** [comment]
Thanks so much for such a quick response! We'll let you know if we have any other issues.
