### ISSUE TITLE
wrong redirection when there is `app` in url

### ISSUE THREAD

**Issue by pashaie** [turquoiseowl/i18n#298]
We have an `app` folder in our project that contains an angularjs application.
When using i18n, urls that start with `app` (which is all our code base minus vendor libraries) redirect to wrong url.

For example  `/app/main.js` is redirected to `/en/main.js` instead of `/en/app/main.js`
As far as I can see, `app` is somehow a keyword, if we change `app` to something else, e.g. `appx`, it works just fine.

thanks in advance.

**Comment by turquoiseowl** [comment]
Yes, 'app' is being interpreted as a language tag. Please see #289 for explanation and how to resolve.

**Comment by pashaie** [comment]
thanks
