### ISSUE TITLE
Postbuild grabs nuggets from all my projects

### ISSUE THREAD

**Issue by rares-p** [turquoiseowl/i18n#299]
Hi,
I have a project that works great with i18n. Thanks for that. :)

I now started a second project with i18n. The problem I have is after building, when the po files are generated they contain all the nuggets from the other project as well as the ones from the new one.

I may be missing something here. Could you please shed some light?

Thanks,
Rares

**Comment by turquoiseowl** [comment]
I'm pleased i18n has been working for you.

 

Have you looked at the i18n.DirectoriesToScan appSetting. Maybe it needs to point to folders lower down the hierarchy for each project? A bit on that in the readme.

 

Sent from my ZX Spectrum

**Comment by rares-p** [comment]
Thanks,

works good like this:
_<add key="i18n.DirectoriesToScan" value="~\.." />_
it used to be:
_<add key="i18n.DirectoriesToScan" value=".." />_

Cheers
