### ISSUE TITLE
Generated po[t] Comments and References

### ISSUE THREAD

**Issue by Sshnyari** [turquoiseowl/i18n#304]
Is it possible to add a config option that allows to specify either we want to generate PO/POT files with or without references (and thus distinct comments if any) ?

A light version of po files (without paths to sources) can be nice to hand over to external translators
Also, a lot of conflicts can be generated if the po/pot files are in git

**Comment by Sshnyari** [comment]
as a workaround, we currently reload TemplateItems, clear all references (except one, otherwise it will be commented) and duplicated comments in a custom posttbuild task (instead of the original one)

**Comment by turquoiseowl** [comment]
Please feel free to submit PR.

**Comment by Sshnyari** [comment]
I think we can close this issue now
