### ISSUE TITLE
messages.po customization

### ISSUE THREAD

**Issue by Sshnyari** [turquoiseowl/i18n#305]
Is there a way to customize the names of the po[t] files or use multiple files as translation source ?

Multiple file can be useful if you want to split wordings into categories/contexts and load only the needed ones instead of having one huge po file to maintain.

**Comment by turquoiseowl** [comment]
Not supported as it stands. Agains, feel free to submit PR. Thanks.

**Comment by Sshnyari** [comment]
Here is a small patch for customizing po/pot filename.

For the multiple files feature, what do you think about it in your end ?

[file.txt](https://github.com/turquoiseowl/i18n/files/569711/file.txt)

**Comment by Sshnyari** [comment]
Here is a quick patch for including multiple po files (it includes the previous patch)
[file.txt](https://github.com/turquoiseowl/i18n/files/569954/file.txt)

**Comment by ajbeaven** [comment]
This would be _awesome_. 

It would also be nice to be able to tag nuggets with a category and have PostBuild generate separate files that only include translations in the specified category. 

My use case is that an administration panel on my site only requires one translation but the public facing side of the site requires many different translations.

**Comment by turquoiseowl** [comment]
https://github.com/turquoiseowl/i18n#po-customization.
