### ISSUE TITLE
messages.po picking up external .po files

### ISSUE THREAD

**Issue by tOmoness** [turquoiseowl/i18n#313]
With the addition of using external .po files in the latest build I thought I'd give it go. I set up one called external.po in my locale folder and added some entries, but upon building and running the post build generator it picks up the entries from my external .po file and places them in the messages.po file as commented out entries.

Is this the desired effect?

**Comment by Sshnyari** [comment]
I don't think so
I'll look into it

**Comment by tOmoness** [comment]
@Sshnyari bit more info... So we need to translate dynamic data (not known until run time), so we made a po file that would contain the dynamic data. Then when the PostBuild generator runs it takes the translations from the dynamic data po file and adds them to messages.po commented out because they don't exist in code. (Hope that helps a bit)

**Comment by Sshnyari** [comment]
Thanks for the info
I added a fix to ignore other po files during postbuild
see #315

**Comment by tOmoness** [comment]
@Sshnyari thanks for taking a look at that!

**Comment by turquoiseowl** [comment]
Can we close this issue?

**Comment by tOmoness** [comment]
Yes we can. :)
