### ISSUE TITLE
angularjs kendojs [[[ being converted

### ISSUE THREAD

**Issue by apiercy78** [turquoiseowl/i18n#327]
I have been using this without fail for the longest time but now when I try to include Kendo JS or some AngularJS scripts I am getting Unexpected symbol error ].

Looks like the JS is still being translated at run time even though I have outgoing and Incoming filters set as below:

            UrlLocalizer.IncomingUrlFilters += delegate(Uri url)
            {
                if (url.LocalPath.ToLower().Contains("bundles") || url.LocalPath.ToLower().Contains("content") || url.LocalPath.ToLower().Contains("scripts"))
                {
                    return false;
                }
                return true;
            };

            UrlLocalizer.OutgoingUrlFilters += delegate(string url, Uri currentRequestUrl)
            {
                Uri uri;
                if (Uri.TryCreate(url, UriKind.Absolute, out uri) || Uri.TryCreate(currentRequestUrl, url, out uri))
                {
                    if (uri.LocalPath.ToLower().Contains("bundles") || uri.LocalPath.ToLower().Contains("content") || uri.LocalPath.ToLower().Contains("scripts"))
                    {
                        return false;
                    }
                }
                return true;
            };

I have included blacklist paths in the webconfig also.

**Comment by turquoiseowl** [comment]
Using the default nugget markup can conflict with JavaScript arrays. Have you considered alternative sequences? I use ```[#[message]#]``` for this reason. 

https://github.com/turquoiseowl/i18n#nugget-markup-customization

**Comment by apiercy78** [comment]
Thanks for your reply, I was able to fix the issue by adding in blacklists for my bundles and moving the i18n code in global.asax to after the registration logic.


Alisdair

________________________________
