### ISSUE TITLE
i can't use string with params on view `@_("hello {0}", Model.Name) is not defined

### ISSUE THREAD

**Issue by mahmut-gundogdu** [turquoiseowl/i18n#342]
hi. it is my first project with i18n. i love this liblary. but i have a problem. 
i find solution for my question in there : https://github.com/turquoiseowl/i18n/issues/35#issuecomment-13239982

but `@_("hello {0}","world") is not working.`
is id deprecated. i dont want to use like that 
`@string.Format("[[[Sign up or in using your %0 account|||{0}]]]", p.DisplayName)`

**Comment by turquoiseowl** [comment]
Yes, i18n v2 fully replaced the normal GetText method of marking up messages (still in i18n v1) with the new nugget syntax.
