### ISSUE TITLE
Translate wont works when file havent comment lines#:? 

### ISSUE THREAD

**Issue by gilbertogwa** [turquoiseowl/i18n#351]
Why the translate works only when POs files have comments lines (with #: characters )? Can you update documments with this information? Apps that generates POs files don't include comments by default...

Won't works:

msgid "I am a text"
msgstr ""

Works:

#:
msgid "I am a text"
msgstr ""

**Comment by calway** [comment]
Seems I ran into this when testing a console app as well. After adding these and changing nothing else in the sample from @ajbeaven it suddenly worked

**Comment by adrinr** [comment]
I ran into this problem, po files don't work if the optional comments don't exist

**Comment by turquoiseowl** [comment]
Happy to re-open. As to investigating, I can't commit to anything just now.

Please feel free to submit a PR with fix. Thanks.

**Comment by vhatuncev** [comment]
@turquoiseowl this can be closed.
