### ISSUE TITLE
Is there a method or property to obtain the selected language?

### ISSUE THREAD

**Issue by beckjin** [turquoiseowl/i18n#353]
![image](https://user-images.githubusercontent.com/7261408/30060960-06ebbae6-9278-11e7-95d8-47d45fab728e.png)

As follows:
```
Accept-Language:en-GB,en-US;q=0.8,en;q=0.6
```

```
Accept-Language:en-US,zh-CN;q=0.8,zh;q=0.6,en;q=0.4
```
I want to get the language that has been matched.

**Comment by turquoiseowl** [comment]
``` The GetPrincipalAppLanguageForRequest extension method to HttpContext can be called to access the PAL of the current request. ```

That should be it.
