### ISSUE TITLE
i18n.POTGenerator build error: warning MSB3283: Cannot find wrapper assembly for type library "EnvDTE100"

### ISSUE THREAD

**Issue by turquoiseowl** [turquoiseowl/i18n#357]
Building i18n on Visual Studio 2013 wirh Visual Studio 2013 SDK installed.

Full error:

```
C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(2234,5): warning MSB3283: Cannot find wrapper assembly for type library "EnvDTE100". Verify that (1) the COM component is registered correctly and (2) your target platform is the same as the bitness of the COM component. For example, if the COM component is 32-bit, your target platform must not be 64-bit.
```

The problem began to occur after installation of VS 2017 on same build PC.

Seems to be a known issue:

https://developercommunity.visualstudio.com/content/problem/15434/cannot-find-wrapper-assembly-for-type-library-envd.html

Repaired VS 2013 installation - No difference

Reinstalled VS 2013 SDK - No difference

Removed and re-added the project reference to EnvDTE100 - This succeeded to fix the build. However, this changed the project and not sure whether this introduces a dependency on VS 2017.

Removed reference to EnvDTE100 - Build succeeds. Tested generated VSIX by re-installing and extension into VS2013 - seems to work fine. Suspect the reference is in fact NOT required. Thus reference removed from i18n.POTGenerator.

**Comment by am-moazzeni** [comment]
thanks a lot for your solution :
Removed and re-added the project reference to EnvDTE100 
work for me like oil 👍 
tanks
