### ISSUE TITLE
'LocalizedApplication' does not contain a definition for 'InstallResponseFilter'

### ISSUE THREAD

**Issue by ajbeaven** [turquoiseowl/i18n#359]
I'm trying to set up i18n on a .NET 4.6.1 project using OWIN. `i18n` and `i18n.Adapter.OwinSystemWeb` are both running v2.1.10.

I must be doing something wrong here because I'm getting a compile time error when, in following the readme docs, I enter the following code in `Global.asax` and `Startup.cs`:
```
// 'LocalizedApplication' does not contain a definition for 'InstallResponseFilter'
i18n.LocalizedApplication.InstallResponseFilter(context)
```

I see in `src/i18n/LocalizedApplication.cs` in this project that the method does indeed exist. Do I need to reference something else in particular or add any nuget packages other than those specified above? Are the nuget packages up to date? This was added a number of months ago, so I expect they would be.

Apologies in advance if I'm doing something stupid!

**Comment by turquoiseowl** [comment]
Yes, it was added in v2.1.11-pre002. You need to enable pre-release packages for nuget to see it.

**Comment by ajbeaven** [comment]
Cool, when are you expecting to push this out to the stable package?
