### ISSUE TITLE
"Illegal characters in path" Exception during postbuild event

### ISSUE THREAD

**Issue by muratbaseren** [turquoiseowl/i18n#362]
Web.config BlackList Value ".\js\kendo;.\js\angular;.\*\dist" , given in the readme causes the exception during PostBuild event.

I worked around this problem by changing **i18n.BlackList** value from the original  "**.\js\kendo;.\js\angular;.\*\dist**" to  "**js\kendo;js\angular;dist**"

**Comment by turquoiseowl** [comment]
Does this observation still apply with latest release?

**Comment by turquoiseowl** [comment]
Closing for now. Please re-open is appropriate. Thanks.
