### ISSUE TITLE
Losing translations

### ISSUE THREAD

**Issue by bigbadmad** [turquoiseowl/i18n#363]
We have a very complicated project - Angular front-end consuming a WebAPI back end etc. I have been asked to programmatically set the language the application is in. This works fine but I'm seeing strange problem. If I set the project to German and leave the app running when I come back later it will switch to English. i18n is still running because the square brackets in the nuggets are still being removed. It is like i18n has lost the cache of it's translations? Does anyone have any ideas?

**Comment by bigbadmad** [comment]
It was a different issue than that which appeared

**Comment by sShrek1** [comment]
@bigbadmad care to share? I cant get my frontend to translate files inside v-for (vuejs), same as ng-repeat i guess...
