### ISSUE TITLE
In i18n.langtag using DefaultLanguage other than "en" is not working

### ISSUE THREAD

**Issue by Jenitta-Rachel** [turquoiseowl/i18n#365]
In my MVC application the user can change the language inside the WebApp using the i18n.langtag.
When the default language is set to "en", the redirects according to the user's preference occur normally and everything is working fine, but when setting another default language than "en" (i.e. "es") on Application_Start the user is always redirected to the default language without respecting the set preference.

Am facing the same issue as mentioned in the issue link https://github.com/turquoiseowl/i18n/issues/250 

I just want to know, if the User language is "English(en)" in browser and our Application language we setting by default is "Spanish(es)". Can't we get the default language as spanish ? Because on my startup am getting as "en" eventhough i set "es " in my startup() of global.asax

 i18n.LocalizedApplication.Current.DefaultLanguage = "es-ES";

Can you please provide solution for this?

**Comment by turquoiseowl** [comment]
Do you have a ```locale\en``` folder?

If so, what happens when you delete it?

**Comment by Jenitta-Rachel** [comment]
I have the following structure in my locale folder

![image](https://user-images.githubusercontent.com/36920237/36830982-e87a14b8-1d4b-11e8-9b80-ad5d5bac0b60.png)

If i delete that, all my texts will be in english

**Comment by Jenitta-Rachel** [comment]
Hi,

I have added the following code to resolve my issue after initializing i18n.UrlLocalizer.IncomingUrlFilters += delegate (Uri url),

var cookieLanguage = LanguageTag.GetCachedInstance(i18n.LocalizedApplication.Current.DefaultLanguage);
                            HttpContext.Current.Response.Cookies.Add(new HttpCookie("i18n.langtag")
                            {
                                Value = cookieLanguage.ToString(),
                                HttpOnly = true,
                                Expires = DateTime.UtcNow.AddYears(1)
                            });
                            HttpContext.Current.SetPrincipalAppLanguageForRequest(cookieLanguage);

**Comment by turquoiseowl** [comment]
Thanks for the update. That looks like a good solution. Are you happy to close the issue?

**Comment by Jenitta-Rachel** [comment]
yes am. Thanks for your response @turquoiseowl
