### ISSUE TITLE
Performance issue in my web app due to i18n

### ISSUE THREAD

**Issue by Karthikeyan-tv** [turquoiseowl/i18n#368]
Hi @turquoiseowl ,
I'm using i18n for the last 2 years in my web app and now we're working on the performance improvement.
While profiling my application, we found that the i18n module takes more CPU time compared to other modules. So we've removed i18n from the web app and load tested the app. We got the below results,

25 users with 5 minutes duration
With i18n,
Avg Response time: 348.7 ms
Request pre sec: 44.7RPS
CPU usage: 95%

Without i18n,
Avg Response time: 161.5 ms
Request pre sec: 70.2RPS
CPU usage: 50%

We're using the below keys in the web.config:
   ```
 <add key="i18n.DirectoriesToScan" value=".." />
    <!-- Rel to web.config file -->
    <add key="i18n.WhiteList" value="*.cs;*.cshtml;*.sitemap;*.js" />
    <add key="i18n.BlackList" value=".\SampleReports;.\Scripts\AngularJS;.\Scripts\Bootstrap;.\Scripts\EssentialJS;.\Scripts\Jcrop;.\Scripts\jQuery;" />
    <add key="i18n.NuggetBeginToken" value="[[[" />
    <add key="i18n.NuggetEndToken" value="]]]" />
    <add key="i18n.NuggetDelimiterToken" value="||||" />
    <add key="i18n.NuggetCommentToken" value="////" />
    <add key="i18n.NuggetParameterBeginToken" value="(((" />
    <add key="i18n.NuggetParameterEndToken" value=")))" />

```
Are these results are normal or do you have any suggestion to improve the performance?

**Comment by turquoiseowl** [comment]
Thanks for your question. Those profile results are the first I've seen TBH but don't look unreasonable to me given the nature of the processing i18n is doing. Having said that I'm a bit disappointed in them because an effort was made to make i18n as performant as possible (in .NET) e.g. to reduce the number of object allocations during response processing and string manipulations.

I suppose you could drill down into different responses and number of nuggets contained to get an idea of per-request overhead vs. per nugget overhead. That might indicate areas for investigation.

**Comment by Karthikeyan-tv** [comment]
Hi @turquoiseowl ,

To ensure whether we are having issue only on our MVC application or all the MVC application, we have tested the MVC default template application with and without i18n and found below.

Scenario | CPU usage
---------|------
without i18n | 20%
with i18n (one message to be translatable)| 21% 
with i18n (around 100 message to be to be translatable)|  95%

![load test result](https://by3302files.storage.live.com/y4mDpdDQ-RWoZiMNwR2G4uryB_VMaTpQJP7iWJUuohyeQlNgGlgkpCgbm7ynbGiaj4zdWz7xsdSihbGMKCCKrMCsCoW0yY_GcogZDgsfxw4bdyPPgclS4OcTm5UTMufMp_qrxm9DEppTyl3K8jXLj9SlIAQBVpVFEyRYbn_l7ZUODgtMBLfyE5tVg_pdzeuSOdGdidmdPfWXhWJEOh1FXtAFQ/load-test.png?psid=1&width=1404&height=719)

If you wish, I will attach the sample project which is hosted on azure for load testing

**Comment by turquoiseowl** [comment]
Okay, that is pretty firm confirmation that the CPU usage is related to the nugget message lookup.

I suspect if you can profile the actual process that most of the work will be in the ```i18n.TextLocalizer.LookupText``` method, and nested within that the call to ```ConcurrentDictionary.TryGetValue```. If that is the case I'm stuck for potential optimization ideas as I chose that dictionary on the basis that it was the fastest/most-efficient.

If some other method shows up in a profiler then there may be scope for optimization.

**Comment by turquoiseowl** [comment]
I'm having trouble looking at those results: VS2017, select full time range, expand w3wp.exe node it says 'No user code was running..."
Any chance of a screen shot? I'm particularly interested in what's going on in EarlyUrlLocalizer.

**Comment by Karthikeyan-tv** [comment]
Here is the screenshot,
LookupText:
![LookupText](https://user-images.githubusercontent.com/13327256/40358438-e10acb10-5ddc-11e8-8ed7-682231c3863c.png)

EarlyUrlLocalizer:
![EarlyUrlLocalizer](https://user-images.githubusercontent.com/13327256/40358488-0b17d57e-5ddd-11e8-940a-bc01783aa5f0.png)

**Comment by turquoiseowl** [comment]
If your tests results were involving primarily translations in the i18n default language for the app, perhaps repeat the tests but with a language other than the default.

**Comment by Karthikeyan-tv** [comment]
Hi @turquoiseowl ,

Yes, you're correct. This high CPU usage is due to using the default language without the specific translation and it works well with specific translation files.

![performance](https://user-images.githubusercontent.com/13327256/40597234-ce86197e-625d-11e8-8aef-564e3ba9091e.png)

Thanks for your support!

**Comment by turquoiseowl** [comment]
Okay, thanks for reporting back.

I've modified the cache dependency code to be more sensible which will remove the difference between default and non-default languages. That is now on top of master branch and on Nuget as v2.1.12-pre002 if you could give it a try.

One other thing: you mentioned a sample webapp. That is something missing from the i18n project so would it be possible for you to contribute that project as a Pull Request? Would be most appreciated.
