### ISSUE TITLE
.vue files not getting translated?

### ISSUE THREAD

**Issue by sShrek1** [turquoiseowl/i18n#371]
I am using VueJS with asp.net webforms and pot-files are not updating while building. 

Is VueJS not compatible? 

My .vue files are under Root/Scripts/app/component and this is my whitelist values:

`    <add key="i18n.WhiteList" value="*.cs;*.cshtml;*.sitemap;*.js;*.aspx; *.vue; .\*\*\components" />`

EDIT: Is it possible getting some .txt file into messages.po while postbuilding?
This way i think it will work..

**Comment by turquoiseowl** [comment]
Are other JS files translating? I'm not aware of anything specific to VueJS.

**Comment by sShrek1** [comment]
@turquoiseowl I dont think so, i just added `var test = '[[[Random test]]]'` and my pot files didnt updated. 
When i run the project, the '[[[ ]]]' around the JS words is not showing, i guess i18n is working then?
Can it be some compiler or something?

Maybe i've missed something? Here is how i set it up. Using version 2.1.11 

`<httpModules>
      <add name="i18n.LocalizingModule" type="i18n.LocalizingModule, i18n" />
    </httpModules>`

`    <modules>
      <add name="i18n.LocalizingModule" type="i18n.LocalizingModule, i18n" />
    </modules>`
** <AppSettings>**
```
 <add key="i18n.DisableReferences" value="false"/>
<add key="i18n.GenerateTemplatePerFile" value="false"/>
<add key="i18n.LocaleOtherFiles" value="translate" />
<add key="i18n.DirectoriesToScan" value=".." />
 <!-- Rel to web.config file -->
<add key="i18n.WhiteList" value="*.cs;*.cshtml;*.sitemap;*.js;*.aspx; *.vue;translate.txt;.\*\*\components" />
<add key="i18n.BlackList" value=".\js\kendo;.\js\angular;dist" />
<add key="i18n.AvailableLanguages" value="sv;en"/>
```

**Global.asax**
```
i18n.LocalizedApplication.Current.DefaultLanguage = "en";
UrlLocalizer.UrlLocalizationScheme = i18n.UrlLocalizationScheme.Void;
```

> Are other JS files translating? I'm not aware of anything specific to VueJS.

**Comment by turquoiseowl** [comment]
If you have ```[[[hello]]]``` in a ```.cs``` file do corresponding messsages appear in POT and PO files?

Same for ```.js``` files?

You have a SPACE before ```*.vue``` in the WhiteList setting. Does removing that help?

**Comment by turquoiseowl** [comment]
Another thing: source files need to be UTF-8.

**Comment by sShrek1** [comment]
@turquoiseowl Removed the whitespace before `*.vue` and it's working! Damn that thing drived me crazy!
Is it possible to get static files translated? Have some text strings in db, is it possible to have a translation.txt file for these?

**Comment by turquoiseowl** [comment]
I'm not clear what you mean. Please open a new issue about that.
