### ISSUE TITLE
"Localization of outgoing URIs" feature issue in version 2.1.13

### ISSUE THREAD

**Issue by pheurteladding** [turquoiseowl/i18n#374]
Hi,
We are using your great plugin in our project, and we try to keep it up-to date. But in the latest release (2.1.13 (20180707)) it seems there is a problem in the **localization of outgoing URIs** feature.
For example, I have a vendor .js file containing: `this._baseHref=""`; and this emtpy javascript char is now filled with some localized URI. The problem did not appear with version 2.1.11. It also does not appear if the empty string is coded with simple quotes instead of double quotes, but as the script comes from another external package, we cannot change its content.

**Comment by turquoiseowl** [comment]
Thanks for reporting.

I've just published 2.1.14 which should fix it for you.

Let me know if not. Cheers

**Comment by pheurteladding** [comment]
Thank you a lot for this very fast release!
It works great again.
