### ISSUE TITLE
"Localization of outgoing URIs" feature issue for relative paths

### ISSUE THREAD

**Issue by pheurteladding** [turquoiseowl/i18n#377]
Hello,

I hope your summer is going well.
I encounter an issue when performing localization of relative paths. In my razor CSHTML page i have the html: `<a class="c-link c-link--chevron u-color-secondary" href="Help#faq">[[[Toutes nos questions fréquentes]]]</a>`
and this is precessed into: `<a class="c-link c-link--chevron u-color-secondary" href="/fr/Help#exemples">Toutes nos questions fréquentes</a>`
instead of `<a class="c-link c-link--chevron u-color-secondary" href="Help#exemples">Toutes nos questions fréquentes</a>`
Relative paths (not starting with '/' char) should not be processed.

And thank you again for your work!

**Comment by turquoiseowl** [comment]
Summer's not going too bad thanks.

What's the URL for the request in question? If it doesn't end with a forward slah can you try with the forward slash to see if that makes a difference.

i18n SHOULD convert unrooted URLs into rooted (and relative) ones prefixed with the current langtag.

More info here #286

**Comment by pheurteladding** [comment]
Hi,

Fially I used MVC rooting (via `@Url.Action()` ) to bypass the problem. The problem was proably due to the unrooted conversion feature.
Anyway thank you for your quick reply :-)
