### ISSUE TITLE
Security vulnerability crashes app pool

### ISSUE THREAD

**Issue by Hangarspace** [turquoiseowl/i18n#387]
@turquoiseowl

During some penetration testing of our application, the testers have found a security vulnerability in the i18n library that potentially crashes the app pool. 

I have a fix, but not the contribution rights and presumably its not a great idea to describe the issue in too much detail in public lest somebody decides to hijack this vulnerability.

**Comment by turquoiseowl** [comment]
Thanks for this. New version 2.1.15 including your fix just released to NuGet.
