### ISSUE TITLE
could not translate when using combine string (javascript)

### ISSUE THREAD

**Issue by ck19992** [turquoiseowl/i18n#395]
my javascript able to translate when the string is plain string.
example:
var name = [[[Name]]];

when my string is combine string, it could not translate.
example
var name = "MyName";
var translateName = "[[[" + name + "]]]";

is there any solution for this?

**Comment by turquoiseowl** [comment]
Does this help?:

https://github.com/turquoiseowl/i18n#how-to-get-a-translation-of-a-nugget-in-your-c-code

**Comment by ck19992** [comment]
I think The method in the link is for c#. In javascript I could not translate combine string. Is there any better solution to solve?

**Comment by turquoiseowl** [comment]
Quite right, sorry, misssed that.

For javascript, the script that the browser receives is all pre-translated by i18n. i18n is intended for ASP.NET webapps where the dynamic stuff tends to happen on the server. There are other equivalent libraries for when the page is generated in the browser.

There may be a workaround if you can explain further what you are attempting to do - that is why can't you just code ```[[[MyName]]]```?

**Comment by ck19992** [comment]
Understand. Thanks for your help. 😊
