### ISSUE TITLE
null check missing for httpcontext.response.contenttype

### ISSUE THREAD

**Issue by scoroop** [turquoiseowl/i18n#401]
https://github.com/turquoiseowl/i18n/blob/395ff751e1c1cbfce396b058e21aa44674dc1bc3/src/i18n/LocalizedApplication.cs#L337

I'm working on legacy app and it turns out it sometimes has null value in contenttype of response. Null-check would make sense here - at the moment as a workaround I just set it explicitly to default value

**Comment by vhatuncev** [comment]
Bug has been fixed already in this [PR](https://github.com/turquoiseowl/i18n/pull/399), but still not merged 😞
