### ISSUE TITLE
Contribution support

### ISSUE THREAD

**Issue by vhatuncev** [turquoiseowl/i18n#404]
Hello @turquoiseowl is it possible to contact with you directly to have a meeting? I have some spare time which I want to spent on this project. What I suggest:
1. Setup automated builds for source code and unit tests
2. Automate Nuget deployment
3. Close top 10 bugs and small/middle level feature
4. Implement support for .NET Core

My email vasiliy.hatunsev@gmail.com
Thank you.

**Comment by turquoiseowl** [comment]
Hi Vasilily. I've just posted a skype chat message to you. Cheers.
