### ISSUE TITLE
2.1.16 doesn't translate some items

### ISSUE THREAD

**Issue by bulente** [turquoiseowl/i18n#414]
Does 2.1.16 has some breaking changes? When I upgraded my project to 2.1.16 from nuget, I saw that some items weren't translated to target languages. For example [[[Class]]] item. Reverting back to 2.1.15 solves the problem. Do I need to change some code for 2.1.16?

**Comment by turquoiseowl** [comment]
No, it is looking like a bug. Sorry about that. See #413

**Comment by turquoiseowl** [comment]
Is your translation for ```[[[Class]]]``` in the PO files?

Are you enabling ```i18n.DisableReferences```?

**Comment by turquoiseowl** [comment]
Hopefully new version 2.1.7 just published fixes this.

**Comment by bulente** [comment]
Confirmed that 2.1.7 fixed the problem. Thanks for the quick response.
