### ISSUE TITLE
Issues with rendering special character inside i18n translation jQuery Rails

### ISSUE THREAD

**Issue by elviajero971** [turquoiseowl/i18n#418]
Hello everybody!

It seams that I'm having issues with apostrophe ' inside i18n translation file inside a Rails App ( ruby '2.7.4'and rails '6.0.3.3')

When I add a translation to a file content/fr.yml, for example: title: "contenu recommandé l'abi", it render the string correctly for the concerned content.html.erb file.

However when I add a similar translation to an another file booking/fr.yml, for example content: "l'heure de l'échange.", it doesn't render the translation properly for the concerned file booking.html.erb
The only known difference to me, is that the second file booking.html.erb is rendered using javascript (specifically jQuery)

The render I have for this transaltion is: l&#39;heure de l&#39;échange

I've tried your syntaxe with &apos; and also title: 'contenu recommandé l''abi' but with no success until now.

It seems that I'm missing something here but I cannot figure out what is...

Any clues ?

**Comment by elviajero971** [comment]
Update! I have finally found a solution using _html
https://guides.rubyonrails.org/i18n.html#using-safe-html-translations

**Comment by turquoiseowl** [comment]
Thanks for the update.
