### ISSUE TITLE
v2.0 - stable?

### ISSUE THREAD

**Issue by wianek** [turquoiseowl/i18n#65]
Hey,
is v2.0 stable? If not, when would it be?

**Comment by jonnybee** [comment]
Would it be possible to ge a pre release package of v2.0 soon on GitHub? 
Should maybe provide both unsigned and signed assemblies? 
I would suggest to only publish i18n and postbuild assemblies in the nuget package. 

I would rather publish integration for VS 2012 (and presumable also at some time add integration for VS2013 and VS2015)  into VisualStudioGallery.com

**Comment by turquoiseowl** [comment]
> I would suggest to only publish i18n and postbuild assemblies in the nuget package.

I'm not quite clear what you mean here.

**Comment by jonnybee** [comment]
I mean without the VS plugins. The basic important part is i18n.dll, i18n.Domain.dll and i18n.Postbuild.exe.

**Comment by turquoiseowl** [comment]
I'm please to say v2 of i18n is now on NuGet. It is versioned as 2.1.1.

i18n.PostBuild and i18n.POTGenerator are also included in the package. After installing the package, these can be located under the ```packages\i18n.2.1.1.0\tools``` folder.

It doesn't do any transforms on web.config. Something for next time.

Any problems, please let me know. Thanks.

**Comment by danielcrenna** [comment]
Good stuff, Martin :)

On Wed, May 27, 2015 at 11:59 AM, Martin Connell <notifications@github.com>
wrote:

> Closed #65 <https://github.com/turquoiseowl/i18n/issues/65>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/turquoiseowl/i18n/issues/65#event-315063767>.
>



-- 
Daniel Crenna
Conatus Creative Inc.
cell:613.400.4286
