### ISSUE TITLE
Comment should make unique nugget

### ISSUE THREAD

**Issue by rickardliljeberg** [turquoiseowl/i18n#90]
If I put the following three in my view

[#[state]#]
[#[state///a condition (i.e. state of mind)]#]
[#[state///geographical state]#]

they will all come together with one translation for them all which is not correct. for instance translating to Swedish the two kinds of state are very different words.

There is a workaround currently that you can write

[#[state]#]
[#[state1///a condition]#]
[#[state2///geographical state]#]

that way they will get unique entries. however then it wont look very pretty if you miss a translation for them.

**Comment by MickeLarsson** [comment]
I'm probably missing something, but I don't get the msgctxt in the .POT-file, only in the .PO-file.

I do have the  ```i18n.MessageContextEnabledFromComment" value="true"``` in my appSettings

Am I doing anything wrong?

**Comment by turquoiseowl** [comment]
Hopefully that fixes it, please let me know.

**Comment by MickeLarsson** [comment]
:+1:
